<HTML>
<HEAD>
<TITLE>HTML TABLE</TITLE>
</HEAD>
<BODY background = "registerimage.jpg">
<FORM ACTION="registerdetails.php" method="get">
<TABLE BORDER="1" ALIGN="CENTER" WIDTH="400"
BGCOLOR="GRAY">
<CAPTION>REGISTRATION YOURSELF!!!</CAPTION>

<TR>
<TH>ENTER YOUR FIRST NAME</TH>
<TD><INPUT TYPE="TEXT" NAME="fname" ID="FN1" MAXLENGTH="10" TITLE="ENTER YOUR FIRST NAME" REQUIRED/></TD>
</TR>

<TR>
<TH>ENTER YOUR LAST NAME</TH>
<TD><INPUT TYPE="TEXT"/></TD>
</TR>

<TR>
<TH>ENTER YOUR PASSWORD</TH>
<TD><INPUT TYPE-"PASSWORD"/></TD>
</TR>

<TR>
<TH>RE-ENTER YOUR PASSWORD</TH>
<TD><INPUT TYPE="PASSWORD"/></TD>
</TR>

<TR>
<TH>ENTER YOUR EMAIL</TH>
<TD><INPUT TYPE="EMAIL" NAME = "mail" /></TD>
</TR>

<TR>
<TH>ENTER YOUR CONTACT NUMBER</TH>
<TD><INPUT TYPE="NUMBER" name = "no"/></TD>
</TR>

<TR>
<TH>ENTER YOUR ADDRESS</TH>
<TD><TEXTAREA ROWS="8" COLS="20"></TEXTAREA></TD>
</TR>

<TR>
<TH>SELECT YOUR GENDER</TH>
<TD>
MALE<INPUT TYPE="RADIO" NAME="G" VALUE="M"/>
FEMALE<INPUT TYPE="RADIO" NAME="G" VALUE="F"/>
</TD>
</TR>

<TR>
<TH>SELECT YOUR HOBBIES</TH>
<TD>
HOBBY1<INPUT TYPE="CHECKBOX"NAME="X[]" VALUE="H"/>
HOBBY1<INPUT TYPE="CHECKBOX"NAME="X[]" VALUE="H2"/>
HOBBY1<INPUT TYPE="CHECKBOX"NAME="X[]" VALUE="H3"/>
</TD>
</TR>

<TR>
<TH>SELECT YOUR DOB</TH>
<TD><INPUT TYPE="DATE" name = "db"/></TD>
</TR>

<TR>
<TH>SELECT YOUR COUNTRY</TH>
<TD>
<SELECT NAME="COUNTRY">
<OPTION VALUE=SELECTED="SELECTED" DISABLED="DISABLED">SELECT YOUR COUNTRY</OPTION>
<OPTION VALUE="1">INDIA</OPTION>
<OPTION VALUE="2">PAKISTAN</OPTION>
</SELECT>
</TD>
</TR>

<TR>
<TH>UPLOAD YOUR RESUME</TH>
<TD><INPUT TYPE="FILE"/></TD>
</TR>

<TR>
<TD COLSPAN="2" ALIGN="CENTER"><INPUT TYPE="SUBMIT"
VALUE="SAVE MY DATA"/>
<INPUT TYPE="RESET" VALUE ="RESET DATA"/>
</TD>
</TR>
</TABLE>
</FORM>

</BODY>
</HTML>
